abbrevs:
  - name: git
    abbr: g
    snippet: git

  - name: gb
    abbr: gb
    snippet: git branch

  - name: (git) branch
    abbr: b
    snippet: branch
    context: '^git\s'
    global: true

  - name: gs
    abbr: gs
    snippet: git status

  - name: (git) status
    abbr: st
    snippet: status
    context: '^git\s'
    global: true

  - name: gsw
    abbr: gsw
    snippet: git switch B

  - name: (git) switch
    abbr: sw
    snippet: switch B
    context: '^git\s'
    global: true

  - name: grs
    abbr: grs
    snippet: git restore

  - name: (git) restore
    abbr: res
    snippet: restore
    context: '^git\s'
    global: true

  - name: greb
    abbr: greb
    snippet: git rebase

  - name: (git) rebase
    abbr: reb
    snippet: rebase
    context: '^git\s'
    global: true

  - name: gp
    abbr: gp
    snippet: git pull

  - name: (git) pull
    abbr: p
    snippet: pull
    context: '^git\s'
    global: true

  - name: gP
    abbr: gP
    snippet: git push

  - name: (git) push
    abbr: P
    snippet: push
    context: '^git\s'
    global: true

  - name: (git push) --force-with-lease
    abbr: f
    snippet: --force-with-lease
    context: '^git\spush\s'
    global: true

  - name: gl
    abbr: gl
    snippet: git log --pretty=format:"%C(auto)%h (%C(blue)%cd%C(auto))%d %s %Cblue" --date=format:"%Y/%m/%d %H:%M:%S" -n 10

  - name: gcm
    abbr: gcm
    snippet: git commit -m '{}'

  - name: (git) commit
    abbr: cm
    snippet: commit
    context: '^git\s'
    global: true

  - name: (git commit) -m
    abbr: m
    snippet: -m '{}'
    context: '^git\scommit\s'
    global: true

  - name: (git commit) --amend --no-edit
    abbr: am
    snippet: --amend --no-edit
    context: '^git\scommit\s'
    global: true

  - name: gco
    abbr: gco
    snippet: git checkout

  - name: (git) checkout
    abbr: co
    snippet: checkout
    context: '^git\s'
    global: true

  - name: d
    abbr: d
    snippet: docker

  - name: dc
    abbr: dc
    snippet: docker compose

  - name: (docker) compose
    abbr: c
    snippet: compose
    context: '^docker\s'
    global: true

  - name: (docker) (compose) up
    abbr: up
    snippet: up -d
    context: '^docker\scompose\s'
    global: true

  - name: (docker) (compose) d
    abbr: d
    snippet: down
    context: '^docker\scompose\s'
    global: true

  - name: (docker) (compose) reset
    abbr: reset
    snippet: down && docker compose up -d
    context: '^docker\scompose\s'
    global: true

  - name: awk '{print $1}'
    abbr: ".1"
    snippet: awk '{print $1}'

  - name: vi
    abbr: vi
    snippet: nvim

  - name: less
    abbr: less
    snippet: bat --paging always

  - name: ls
    abbr: ls
    snippet: eza --icons auto

  - name: ll
    abbr: ll
    snippet: eza --icons auto -la

  - name: tf
    abbr: tf
    snippet: terraform

  - name: gg
    abbr: gg
    snippet: lazygit

  - name: cursor
    abbr: c
    snippet: cursor

  - name: claude
    abbr: cc
    snippet: claude

  - name: cursor-agent
    abbr: ca
    snippet: cursor-agent
