[font]
size = 16.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Regular Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij -l welcome"]

[keyboard]
bindings = [{ key = "Return", mods = "Shift", chars = "\n" }]
